stages:
  - build
  - deploy

build:
  stage: build
  image: jenkins/jenkins:lts
  script:
    - java -version
    - mvn -version
    - curl -X POST http://jenkins:8080/job/myjob/build --user jenkins:mysecretpassword
  artifacts:
    paths:
      - target/*.war

deploy:
  stage: deploy
  image: tomcat:9.0-jre11
  script:
    - curl -T target/*.war "http://tomcat:8080/manager/text/deploy?path=/myapp&update=true" --user admin:admin
